version: '3.1'

services:
  run:
    image: ruby:latest
    command: ./init.sh 2
    ports:
     - "27001:27001"
     - "27002:27002"
  mongo:
    image: mongo
    command: ./scripts/run_replicaset.sh 2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
